/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AInput: typeof import('ant-design-vue/es')['Input']
    Artists: typeof import('./src/components/Artists.vue')['default']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ATable: typeof import('ant-design-vue/es')['Table']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    Download: typeof import('./src/components/Download.vue')['default']
    Edit: typeof import('./src/components/Edit.vue')['default']
    Multiselect: typeof import('./src/components/Multiselect.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    Tags: typeof import('./src/components/Tags.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
    Wave: typeof import('./src/components/Wave.vue')['default']
  }
}
